Exercise 1
elefus/epam-lab-java8-11-2017 pull request #1
Opened 2017-10-31 14:21 UTC by MihailPoplavkov

2017-10-31 14:27 UTC, AleksandrRadchenko requested changes

2017-10-31 14:27 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +                return person.getAge() == 30;
NPE?

2017-10-31 14:27 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
>          Person person = null;
Not needed

2017-10-31 14:27 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +                        return person.getAge() == 30;
NPE?

2017-11-01 09:09 UTC, turenkoaa approved these changes

2017-11-01 09:11 UTC, ferventdev approved these changes

2017-11-01 19:36 UTC, merged