lambda.part3.exercise2 (Turenko)
elefus/epam-lab-java8-11-2017 pull request #103
Opened 2017-11-21 16:04 UTC by turenkoaa

2017-11-30 14:21 UTC, elefus requested changes
Исправь мерж-конфликты.

2017-11-30 14:21 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise2.java
> +            for (T item:source) newSource.add(mapping.apply(item));
Для перебора всех элементов коллекции можно воспользоваться `Collection.forEach`

2017-11-30 14:21 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise2.java
> +                                 .map(person -> person.getFirstName() + ' ' + person.getLastName())
В классе `Person` есть метод `getFullName`.

2017-12-22 15:19 UTC, turenkoaa commented
check please this pull request for merging. I can not find differences from turenko branch.

2017-12-24 09:17 UTC, elefus approved these changes

2017-12-24 09:18 UTC, merged