Streams.part1.exercise1 (Bevad)
elefus/epam-lab-java8-11-2017 pull request #105
Opened 2017-11-23 18:50 UTC by Ksenomorfa

2017-11-25 20:47 UTC, AleksandrRadchenko approved these changes
Reviewed part1/exercise/Exercise1.java

2017-11-25 20:47 UTC, Alsturm commented on src/test/java/streams/part1/exercise/Exercise1.java
> +                        .anyMatch(job -> job.getEmployer().equals("EPAM")))
As alternative we can use:
`.map(JobHistoryEntry::getEmployer)`
`.anyMatch("EPAM"::equals)`

2017-11-25 20:47 UTC, Alsturm commented on src/test/java/streams/part1/exercise/Exercise1.java
> +                .findFirst().get();
I would suggest to use `.min()` instead of `.sorted().findFirst()`

2017-11-30 14:30 UTC, elefus approved these changes

2017-11-30 14:30 UTC, elefus commented on src/test/java/streams/part1/exercise/Exercise1.java
> +                .filter(employee -> employee.getJobHistory().stream()
Стоит ли использовать стримы, чтобы получить первый элемент списка?)

2017-11-30 14:30 UTC, elefus commented on src/test/java/streams/part1/exercise/Exercise1.java
> +                .findFirst().get();
`min` является более наглядной операцией, демонстрирующей ожидания относительно результата.

2017-11-30 14:30 UTC, elefus requested changes
Исправить мерж-конфликт

2017-11-30 15:11 UTC, Ksenomorfa commented
@elefus  мерж конфликт исправлен.

2017-12-04 11:23 UTC, elefus approved these changes

2017-12-04 11:23 UTC, merged