Streams.part1.exercise2(Kuras)
elefus/epam-lab-java8-11-2017 pull request #112
Opened 2017-11-27 11:57 UTC by Onoxider

2017-12-04 13:55 UTC, elefus requested changes
Посмотри замечания

2017-12-04 13:55 UTC, elefus commented on src/test/java/streams/part1/exercise/Exercise2.java
> +        for (Person person : candidates.keySet()) {
Для перебора всех пар и обновления значений больше подходит метод `replaceAll`

2017-12-04 13:55 UTC, elefus commented on src/test/java/streams/part1/exercise/Exercise2.java
> +        for (Person person : candidates.keySet()) {
К сожалению, это некорректная реализация, т.к. в процессе итерации по `keySet` ты будешь модифицировать исходную мапу и это приведет к `ConcurrentModificationException`.

2017-12-07 14:35 UTC, elefus requested changes
Посмотри замечание

2017-12-07 14:35 UTC, elefus commented on src/test/java/streams/part1/exercise/Exercise2.java
> +                                                                        : null);
* Предыдущее решение ты почему-то оставил)
* Предложенным решением ты задашь значение `null` для всех ключей, удовлетворяющих условию, а не удалишь их.

Удалить можно следующим способом:
`new HashSet<>(candidates.keySet()).forEach(person -> candidates.compute(person, (key, status) -> person.getAge() > 21 ? Status.ACCEPTED : null));`

2017-12-10 09:19 UTC, Onoxider commented on src/test/java/streams/part1/exercise/Exercise2.java
> +                                                                        : null);
А, всё я понял да, первая реализация была неудобная потому что я foreach делал обычным способом, а через replaceAll действительно ключ не удалялся. Пара удаляется только через compute тут, угу, поправил

2017-12-11 10:51 UTC, elefus approved these changes

2017-12-11 10:52 UTC, merged