Lambda.part3.exercise1 (Elagin)
elefus/epam-lab-java8-11-2017 pull request #115
Opened 2017-11-27 15:48 UTC by AndreyElagin

2017-12-05 12:34 UTC, elefus requested changes
Посмотри замечания

2017-12-05 12:34 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +            return String.format("%s %s", person.getFirstName(), person.getLastName());
В классе `Person` имеется метод `getFullName`

2017-12-05 12:34 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +                employee -> stringLengthExtractor.apply(fullNameExtractor.apply(employee));
Комбинацию функций следует производить с использованием `andThen`

2019-07-03 22:20 UTC, AndreyElagin commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +            return String.format("%s %s", person.getFirstName(), person.getLastName());
Да мне похую.

2019-07-03 22:21 UTC, AndreyElagin commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +                employee -> stringLengthExtractor.apply(fullNameExtractor.apply(employee));
ты чо ты чо, я на скале пишу и умею комбинировать функции

2019-07-03 22:21 UTC, AndreyElagin commented
Мержи блять мое дз как есть, заебался ждать уже

2019-07-04 08:23 UTC, AleksandrRadchenko commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +                employee -> stringLengthExtractor.apply(fullNameExtractor.apply(employee));
Так и барабухи образоваться могут...

2019-07-06 04:44 UTC, closed without merging