Streams.part2.exercise2 (Radchenko)
elefus/epam-lab-java8-11-2017 pull request #118
Opened 2017-11-27 22:18 UTC by Alsturm

2017-12-02 19:52 UTC, ferventdev approved these changes

2017-12-05 12:57 UTC, elefus requested changes
Посмотри замечания

2017-12-05 12:57 UTC, elefus commented on src/test/java/streams/part2/exercise/Exercise2.java
> +        Map<String, Person> result =
Сейчас решение в процессе работы создает две "промежуточных" мапы. Можно обойтись одной.

2017-12-05 12:57 UTC, elefus commented on src/test/java/streams/part2/exercise/Exercise2.java
> +                                        .map(jobEntry -> new EmployerPersonDuration(new EmployerPersonPair(jobEntry.getEmployer(), e.getPerson()), jobEntry.getDuration())))
Суммирование общего времени работы сотрудника на конкретного работодателя можно производить здесь - размер обрабатываемого стрима в таком случае будет меньше.

2018-01-12 15:33 UTC, Alsturm commented on src/test/java/streams/part2/exercise/Exercise2.java
> +                                        .map(jobEntry -> new EmployerPersonDuration(new EmployerPersonPair(jobEntry.getEmployer(), e.getPerson()), jobEntry.getDuration())))
Посмотрели, количество операций то же, просто порядок действий изменен.

2018-01-12 15:33 UTC, Alsturm commented
Избавился от лишней промежуточной мапы.

2018-01-15 10:15 UTC, elefus approved these changes

2018-01-15 10:15 UTC, merged