Spliterator.part1.ForkJoinPool (Radchenko)
elefus/epam-lab-java8-11-2017 pull request #127
Opened 2017-11-28 14:20 UTC by Alsturm

2017-11-28 14:37 UTC, elefus commented on src/test/java/spliterator/part1/exercise/forkjoinpool/FJPSumIntArrayExample.java
> +    private static int threadCount = 0;
Не-volatile shared переменная)

2017-11-28 14:38 UTC, elefus commented on src/test/java/spliterator/part1/exercise/forkjoinpool/FJPSumIntArrayExample.java
> +            threadCount++;
Посчитает количество созданных объектов.
Но не на каждом ты делаешь fork и не каждый отдается новому потоку ;-)

2017-11-28 14:46 UTC, Alsturm commented on src/test/java/spliterator/part1/exercise/forkjoinpool/FJPSumIntArrayExample.java
> +    private static int threadCount = 0;
Хых :)
![image](https://user-images.githubusercontent.com/24558458/33325669-fcd0348c-d463-11e7-9acb-66443fa576d8.png)

2017-11-28 15:53 UTC, Alsturm commented on src/test/java/spliterator/part1/exercise/forkjoinpool/FJPSumIntArrayExample.java
> +            threadCount++;
Перенес увеличение счетчика к fork'у

2017-11-28 15:53 UTC, Alsturm commented on src/test/java/spliterator/part1/exercise/forkjoinpool/FJPSumIntArrayExample.java
> +    private static int threadCount = 0;
Изменил int -> AtomicInteger

2017-12-05 13:34 UTC, elefus requested changes
Исправить замечание

2017-12-05 13:34 UTC, elefus commented on src/test/java/spliterator/part1/exercise/forkjoinpool/FJPSumIntArrayExample.java
> +                return left.join() + right.compute();
Неправильный порядок вызова методов.
Сначала текущий поток дождется выполнения вычисления левой части, а потом приступит к вычислению правой -> потерян паралеллизм.

2017-12-26 23:55 UTC, Alsturm commented on src/test/java/spliterator/part1/exercise/forkjoinpool/FJPSumIntArrayExample.java
> +                return left.join() + right.compute();
Исправил

2017-12-27 08:38 UTC, elefus approved these changes

2017-12-27 08:38 UTC, merged