Lambda.part3.exercise1 (Leznikova)
elefus/epam-lab-java8-11-2017 pull request #137
Opened 2017-11-28 19:10 UTC by NataliaLeznikova

2017-12-05 13:56 UTC, elefus requested changes
Посмотри замечания

2017-12-05 13:56 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, String> fullNameExtractor = employee -> employee.getPerson().getFirstName() + " " + employee.getPerson().getLastName();
Можно воспользоваться ссылкой на метод `getFullName`, объявленный в классе `Person`.

2017-12-05 13:56 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<String, Integer> stringLengthExtractor = string -> string.length();
Можно воспользоваться ссылкой на метод `length`, объявленный в классе `String`.

2018-01-14 17:57 UTC, NataliaLeznikova commented
Спасибо, исправила :)

2018-01-15 10:16 UTC, elefus approved these changes

2018-01-15 10:16 UTC, merged