Streams.part1.exercise2 (Elagin)
elefus/epam-lab-java8-11-2017 pull request #140
Opened 2017-11-29 23:12 UTC by AndreyElagin

2017-12-05 14:09 UTC, elefus requested changes
Посмотри комментарий

2017-12-05 14:09 UTC, elefus commented on src/test/java/streams/part1/exercise/Exercise2.java
> +                        oldStatus == null ? newValues.put(key, newStatus) : oldStatus));
Так как исходная мапа в качестве значений не содержит `null` - функция преобразования всегда будет просто возвращать `oldStatus`.

2018-01-11 22:32 UTC, AndreyElagin commented on src/test/java/streams/part1/exercise/Exercise2.java
> +                        oldStatus == null ? newValues.put(key, newStatus) : oldStatus));
Поправил вроде

2018-01-11 22:34 UTC, daddyingrave reviewed
готово

2018-01-15 10:17 UTC, elefus approved these changes

2018-01-15 10:17 UTC, merged