Streams.part2.exercise2 (Shevkunenko)
elefus/epam-lab-java8-11-2017 pull request #154
Opened 2017-12-02 19:47 UTC by ferventdev

2017-12-05 16:39 UTC, elefus requested changes
Посмотри комментарии

2017-12-05 16:39 UTC, elefus commented on src/test/java/streams/part2/exercise/Exercise2.java
> +    public void greatestExperiencePerEmployer() {
Сейчас решение в процессе работы создает две "промежуточных" мапы. Можно обойтись одной.

2017-12-05 16:39 UTC, elefus commented on src/test/java/streams/part2/exercise/Exercise2.java
> +                                 (p1, p2) -> p1.getDuration() > p2.getDuration() ? p1 : p2,
Эту операцию можно выполнять с помощью коллектора maxBy

2017-12-23 14:33 UTC, ferventdev commented
Замечание исправил. Применил коллектор MaxBy.

2017-12-27 09:05 UTC, elefus approved these changes

2017-12-27 09:05 UTC, elefus commented on src/test/java/streams/part2/exercise/Exercise2.java
> +                                 HashMap::new,
По умолчанию и так используется HashMap

2017-12-27 09:05 UTC, merged