Lambda.part2.exercise2
elefus/epam-lab-java8-11-2017 pull request #164
Opened 2017-12-05 13:44 UTC by FLYABRWAY

2017-12-05 15:28 UTC, elefus requested changes
Посмотри замечания

2017-12-05 15:28 UTC, elefus commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +    public void personHasNotEmptyLastNameAndFirstNameUsingLogicalOperators() {
По названию метода можно сделать вывод, что при его реализации необходимо воспользоваться методами, объявленными выше.

2017-12-05 15:28 UTC, elefus commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +    public void personHasNotEmptyLastNameAndFirstNameUsingGenericPredicates() {
По названию метода можно сделать вывод, что при его реализации необходимо воспользоваться методами, объявленными выше.

2017-12-07 13:07 UTC, FLYABRWAY commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +    public void personHasNotEmptyLastNameAndFirstNameUsingLogicalOperators() {
Resolved!

2017-12-07 13:07 UTC, FLYABRWAY commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +    public void personHasNotEmptyLastNameAndFirstNameUsingGenericPredicates() {
Resolved!

2017-12-07 14:23 UTC, elefus approved these changes

2017-12-07 14:23 UTC, merged