streams.part1.exercise2(ivanov)
elefus/epam-lab-java8-11-2017 pull request #184
Opened 2017-12-16 18:40 UTC by FLYABRWAY

2017-12-18 09:27 UTC, elefus requested changes
Посмотри комментарии

2017-12-18 09:27 UTC, elefus commented on src/test/java/streams/part1/exercise/Exercise2.java
> +        candidates.entrySet().removeIf(candidate -> candidate.getKey().getAge() < 21);
Можно сделать в один проход с помощью метода `compute`

2017-12-18 09:27 UTC, elefus commented on src/test/java/streams/part1/exercise/Exercise2.java
> +        newValues = Stream.concat(newValues.entrySet().stream(), oldValues.entrySet().stream())
В задании сказано положить в `newValues`, а не создавать новую.

2017-12-20 16:35 UTC, FLYABRWAY commented on src/test/java/streams/part1/exercise/Exercise2.java
> +        candidates.entrySet().removeIf(candidate -> candidate.getKey().getAge() < 21);
Можно. Нужно?

2017-12-21 08:37 UTC, elefus approved these changes

2017-12-21 08:37 UTC, merged