Lambda.part3.exercise1 (Gumeniuk)
elefus/epam-lab-java8-11-2017 pull request #189
Opened 2017-12-17 13:30 UTC by SovietSir

2017-12-18 09:39 UTC, elefus requested changes
Посмотри замечания

2017-12-18 09:39 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = e -> stringLengthExtractor.apply(fullNameExtractor.apply(e));
Объединение функций следует производить через `compose` и `andThen`.

2017-12-18 09:39 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        for (Employee employee : employees) {
В Java8 в интерфейс `Collection` добавили метод `foreach`. Подумай, как его можно применить в этом месте.

2017-12-18 13:54 UTC, SovietSir commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = e -> stringLengthExtractor.apply(fullNameExtractor.apply(e));
Done.

2017-12-18 13:54 UTC, SovietSir commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        for (Employee employee : employees) {
Done.

2017-12-19 08:53 UTC, elefus requested changes
Посмотри замечания

2017-12-19 08:53 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = e -> fullNameExtractor.andThen(stringLengthExtractor).apply(e);
Вызов метода `apply` избыточен, `andThen` уже возвращает подходящую функцию.

2017-12-19 08:53 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        employees.forEach(e -> lengths.add(fullNameLengthExtractor.apply(e)));
А если сделать еще один шаг и не использовать лямбду, воспользовавшись только комбинацией функций и ссылками на методы?

2017-12-20 13:14 UTC, SovietSir commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = e -> fullNameExtractor.andThen(stringLengthExtractor).apply(e);
Fixed.

2017-12-20 13:14 UTC, SovietSir commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        employees.forEach(e -> lengths.add(fullNameLengthExtractor.apply(e)));
Done.

2017-12-20 13:15 UTC, merged