Lambda-Part3_Exercise4_Done
elefus/epam-lab-java8-11-2017 pull request #195
Opened 2017-12-18 16:29 UTC by SovietSir

2017-12-19 10:21 UTC, elefus requested changes
Посмотри комментарии

2017-12-19 10:21 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            return new LazyFlatMapHelper<>(list, Arrays::asList);
Посмотри на `Collections::singletonList`, возможно она лучше подойдет в этом месте.

2017-12-19 10:21 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            return new LazyFlatMapHelper<>(source, compose(rule, t -> Collections.singletonList(mapping.apply(t))));
Последовательный вызов функций с передачей параметров из одной в другую можно заменить на комбинирование этих функций.

2017-12-19 10:21 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +        private <R2> Function<T, List<R2>> compose(Function<T, List<R>> function1, Function<R, List<R2>> function2) {
Действительно ли нужен отдельный метод `compose`, или его можно объединить с `iterationHelper`?

2017-12-19 10:21 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            list.forEach(s -> newList.addAll(function.apply(s)));
Метод `Iterable.forEach` принимает на вход `Consumer`, можно ли его получить в данном случае, используя комбинацию функций?

2017-12-20 11:54 UTC, SovietSir commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            return new LazyFlatMapHelper<>(list, Arrays::asList);
Rewrited.

2017-12-20 15:01 UTC, SovietSir commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            return new LazyFlatMapHelper<>(source, compose(rule, t -> Collections.singletonList(mapping.apply(t))));
Rewrited.

2017-12-20 15:02 UTC, SovietSir commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +        private <R2> Function<T, List<R2>> compose(Function<T, List<R>> function1, Function<R, List<R2>> function2) {
Methods aggregated.

2017-12-20 15:14 UTC, SovietSir commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            list.forEach(s -> newList.addAll(function.apply(s)));
Functions combined.

2017-12-27 08:44 UTC, elefus approved these changes

2017-12-27 08:44 UTC, elefus commented
Отличное решение!
Надеюсь функциональный подход стал чуть-чуть понятнее)

2017-12-27 08:44 UTC, merged