Spliterator.part1.exercise3
elefus/epam-lab-java8-11-2017 pull request #199
Opened 2017-12-26 23:37 UTC by Alsturm

Seems like test for dropWhile had error

2017-12-27 08:30 UTC, elefus requested changes
Реализовать через кастомные сплитераторы

2017-12-27 08:30 UTC, elefus commented on src/main/java/spliterator/part1/example/example3/AdvancedStreamImpl.java
> +    public AdvancedStream<T> takeWhile(Predicate<? super T> predicate) {
Такая реализация получается не ленивой, в то время как операция `takeWhile` является промежуточной и не должна приводить к реальным вычислениям. а лишь возвращает новый стрим.
К тому же создается лишняя коллекция для хранения элементов (они ведь и так хранятся в оригинальном `DataSource`, на основе которого создан стрим.
В качестве примера стоит взять `zipWithIndex` и создать новый сплитератор, который бы добавлял требуемое поведение (реализовать метод `tryAdvance` в нем).

2017-12-27 08:30 UTC, elefus commented on src/main/java/spliterator/part1/example/example3/AdvancedStreamImpl.java
> +    public AdvancedStream<T> dropWhile(Predicate<? super T> predicate) {
Аналогично `takeWhile` текущая реализация не является ленивой.

2018-01-13 15:28 UTC, Alsturm commented on src/main/java/spliterator/part1/example/example3/AdvancedStreamImpl.java
> +    public AdvancedStream<T> takeWhile(Predicate<? super T> predicate) {
Спасибо! Переделал.

2018-01-13 15:28 UTC, Alsturm commented on src/main/java/spliterator/part1/example/example3/AdvancedStreamImpl.java
> +    public AdvancedStream<T> dropWhile(Predicate<? super T> predicate) {
Переделал.

2018-01-14 14:51 UTC, Mikhail-Sosnin approved these changes

2018-01-15 15:42 UTC, merged