Lambda exercise1
elefus/epam-lab-java8-11-2017 pull request #2
Opened 2017-10-31 14:22 UTC by Alsturm

2017-10-31 16:20 UTC, elefus commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +                if (left.getAge() > right.getAge()) result = 1;
Метод сравнения чисел уже реализован в JDK: Integer.compare(int, int)

2017-10-31 16:24 UTC, elefus requested changes

2017-10-31 16:24 UTC, elefus commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Arrays.sort(persons, new Comparator<Person>() {
Можно выполнить всего одну сортировку.
Для этого необходимо объединить два компаратора в один.

2017-10-31 16:58 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +                if (left.getAge() > right.getAge()) result = 1;
Fixed

2017-10-31 16:58 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Arrays.sort(persons, new Comparator<Person>() {
Fixed

2017-11-01 09:01 UTC, ferventdev approved these changes

2017-11-01 19:39 UTC, elefus approved these changes

2017-11-01 19:39 UTC, merged