Streams.part2.exercise1(Poplavkov)
elefus/epam-lab-java8-11-2017 pull request #206
Opened 2018-01-05 09:47 UTC by MihailPoplavkov

2018-01-10 07:15 UTC, elefus requested changes
Посмотри комментарии

2018-01-10 07:15 UTC, elefus commented on src/test/java/streams/part2/exercise/Exercise1.java
> +                .reduce((s1, s2) -> s1 + "\n" + s2)
Для составления строки из элементов стрима следует использовать предназначенный для этого коллектор `Collectors.joining`

2018-01-10 07:15 UTC, elefus commented on src/test/java/streams/part2/exercise/Exercise1.java
> +                            HashSet<Person> set = new HashSet<>(set1);
Операция `collect` описывается как mutable-reduction, следовательно в ней можно модифицировать переданные параметры без создания нового объекта (в отличие от операции `reduce`).

2018-01-10 15:49 UTC, MihailPoplavkov commented on src/test/java/streams/part2/exercise/Exercise1.java
> +                            HashSet<Person> set = new HashSet<>(set1);
Я создаю здесь новый объект, потому что изначально они все Collections.singleton, то есть immutable. 
Наверное, правильнее будет сделать инициализацию просто HashSet-ом и тогда можно обойтись без создания нового объекта, как ты и написал. Сделал так в следующем коммите.

2018-01-11 11:53 UTC, elefus approved these changes

2018-01-11 11:53 UTC, merged