Streams.part2.exercise2 (Turenko)
elefus/epam-lab-java8-11-2017 pull request #216
Opened 2018-01-11 11:08 UTC by turenkoaa

2018-01-11 11:39 UTC, ferventdev approved these changes

2018-01-11 12:16 UTC, elefus requested changes
Внести исправления в метод greatestExperiencePerEmployer

2018-01-11 12:16 UTC, elefus commented on src/test/java/streams/part2/exercise/Exercise2.java
> +                .collect(toMap(Map.Entry::getKey, entry -> entry.getValue().getPerson()));
От создания третьей мапы можно избавиться воспользовавшись цепочкой коллекторов `groupingBy`, `collectingAndThen`, `maxBy`.

2018-01-12 10:20 UTC, turenkoaa commented on src/test/java/streams/part2/exercise/Exercise2.java
> +                .collect(toMap(Map.Entry::getKey, entry -> entry.getValue().getPerson()));
fixed

2018-01-14 14:50 UTC, Mikhail-Sosnin approved these changes

2018-01-15 10:22 UTC, elefus approved these changes

2018-01-15 10:22 UTC, merged