lambda.exercise1 (Turenko)
elefus/epam-lab-java8-11-2017 pull request #3
Opened 2017-10-31 14:35 UTC by turenkoaa

2017-10-31 15:06 UTC, AleksandrRadchenko requested changes

2017-10-31 15:06 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Predicate<Person> isFirstNameAlexChecker = new Predicate<Person>() {
Predicate name irrelevant

2017-10-31 16:24 UTC, elefus commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Predicate<Person> isFirstNameAlexChecker = new Predicate<Person>() {
Копипаст-копипастом, но править надо)

2017-10-31 17:04 UTC, AleksandrRadchenko requested changes

2017-10-31 17:04 UTC, AleksandrRadchenko commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Arrays.sort(persons, new Comparator<Person>() {
You can combine comparators and use only one sort here.

2017-10-31 17:23 UTC, turenkoaa commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Arrays.sort(persons, new Comparator<Person>() {
Thank you, I`ve combined them.

2017-10-31 17:25 UTC, AleksandrRadchenko approved these changes

2017-11-01 08:21 UTC, ferventdev approved these changes

2017-11-01 19:41 UTC, elefus approved these changes

2017-11-01 19:41 UTC, merged