Lambda.part2.exercise1(Poplavkov)
elefus/epam-lab-java8-11-2017 pull request #38
Opened 2017-11-14 13:34 UTC by MihailPoplavkov

2017-11-14 13:49 UTC, ferventdev approved these changes

2017-11-14 16:10 UTC, elefus requested changes
Исправить замечания

2017-11-14 16:10 UTC, elefus commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +        Function<Person, Integer> ageExtractor = Person::getAge;assertEquals(33, ageExtractor.apply(person).intValue());
Почему склеено в одну строку?)

2017-11-14 16:10 UTC, elefus commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +    private static Function<Person, String> getFullName() {
В настоящий момент функциональная сигнатура этого метода:
`() -> (Person, String)`

TODO для этого метода описывала другую сигнатуру:
`Person -> String`

2017-11-14 16:10 UTC, elefus commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +        Function<Person, String> getFullName = getFullName();
Следуя TODO в этом месте необходимо было воспользоваться ссылкой на метод `getFullName`, а не его вызовом.

2017-11-17 11:59 UTC, MihailPoplavkov commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +        Function<Person, Integer> ageExtractor = Person::getAge;assertEquals(33, ageExtractor.apply(person).intValue());
Упс)

2017-11-17 11:59 UTC, MihailPoplavkov commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +    private static Function<Person, String> getFullName() {
@elefus неправильно понял. Исправил

2017-11-17 12:30 UTC, elefus approved these changes

2017-11-17 12:30 UTC, merged