Lambda.part2.task1
elefus/epam-lab-java8-11-2017 pull request #41
Opened 2017-11-14 13:44 UTC by Alsturm

2017-11-14 16:21 UTC, elefus requested changes
Исправить замечания

2017-11-14 16:21 UTC, elefus commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +        BiPredicate<Person, Person> sameAgesChecker = (p1, p2) -> Objects.equals(p1.getAge(), p2.getAge());
Значения, возвращаемые `getAge()` примитивного типа `int` - нет смысла их сравнивать через `Objects.equals`, т.к. они не могут быть `null`. Достаточно выполнить проверку через двойное равно)

2017-11-14 16:21 UTC, elefus commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +        return p.getFirstName() + " " + p.getLastName();
Этот код ведь не скомпилируется)
Возвращаемым значением объявлена `Function<Person, String>` а на самом деле возвращается объект класса `String`.

2017-11-15 15:29 UTC, Alsturm commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +        BiPredicate<Person, Person> sameAgesChecker = (p1, p2) -> Objects.equals(p1.getAge(), p2.getAge());
Thanks, fixed!

2017-11-15 15:30 UTC, Alsturm commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +        return p.getFirstName() + " " + p.getLastName();
Sorry, fixed. 
As far as I remember, tests were green when I create pull request (now I don't know how it could be possible).

2017-11-15 17:16 UTC, Alsturm commented on src/test/java/lambda/part2/exercise/Exercise1.java
> +        return p.getFirstName() + " " + p.getLastName();
Changed method signature from `Function<Person, String>` to `String`.
By the way, IMHO `// TODO метод getFullName: Person -> String` is ambiguous. It's not clear whether we should create `Function<Person, String>` or just ordinary method, returning `String`.

2017-11-17 12:33 UTC, elefus approved these changes

2017-11-17 12:33 UTC, merged