lambda.exercise1 (Elagin)
elefus/epam-lab-java8-11-2017 pull request #5
Opened 2017-10-31 14:47 UTC by AndreyElagin

2017-10-31 15:19 UTC, AleksandrRadchenko requested changes

2017-10-31 15:19 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Arrays.sort(persons);
We are to use comparator here... See test method name :/

2017-11-01 09:08 UTC, ferventdev approved these changes

2017-11-01 19:48 UTC, elefus commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Arrays.sort(persons);
Это был мой косяк что я предусмотрел естественный порядок сортировки в классе.
Действительно, можно не плодить дополнительных сущностей и воспользоваться Arrays.sort без параметров.

2017-11-01 19:48 UTC, merged