Lambda.part3.exercise1 (Shevkunenko)
elefus/epam-lab-java8-11-2017 pull request #58
Opened 2017-11-17 15:20 UTC by ferventdev

2017-11-18 21:36 UTC, AleksandrRadchenko requested changes
Reviewed Lambda.part3.exercise1.
Resolving of conflicts needed.

2017-11-19 16:07 UTC, ferventdev commented
Conflicts resolved.

2017-11-19 16:09 UTC, AleksandrRadchenko approved these changes

2017-11-19 17:34 UTC, Ksenomorfa approved these changes

2017-11-20 10:53 UTC, elefus requested changes
Остался какой-то конфликт в pom.xml

2017-11-20 10:53 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = employee -> stringLengthExtractor.apply(fullNameExtractor.apply(employee));
Комбинировать функции стоит через `andThen`

2017-11-20 14:31 UTC, ferventdev commented
Конфликт в pom.xml я разрешил (почему-то пришлось это делать даже не один раз).
Замечание насчет использования andThen я тоже исправил (см. файл Part3 Excercise1).

2017-11-21 09:39 UTC, elefus approved these changes

2017-11-21 09:39 UTC, merged