Lambda.part3.exercise1 (Bevad)
elefus/epam-lab-java8-11-2017 pull request #59
Opened 2017-11-18 16:46 UTC by Ksenomorfa

2017-11-18 21:38 UTC, AleksandrRadchenko approved these changes
Reviewed Lambda.part3.exercise1

2017-11-19 15:21 UTC, ferventdev approved these changes

2017-11-20 10:54 UTC, elefus requested changes

2017-11-20 10:54 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee,Integer> fullNameLengthExtractor =
Комбинировать функции стоит через andThen

2017-11-20 18:38 UTC, Ksenomorfa commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee,Integer> fullNameLengthExtractor =
Done.

2017-11-21 10:09 UTC, elefus approved these changes

2017-11-21 10:09 UTC, merged