Lambda.part1.exercise1 (Nikolaev)
elefus/epam-lab-java8-11-2017 pull request #63
Opened 2017-11-18 19:18 UTC by usilitel

2017-11-18 22:00 UTC, AleksandrRadchenko requested changes
Reviewed part1/Exercise1.java

2017-11-18 22:00 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +                new Person("Иван", "Мельников", 20),
Seems like irrelevant formatting... (in other places too)

2017-11-18 22:00 UTC, Alsturm commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Arrays.sort(persons, new Comparator<Person>() {
Can be replaced by one combined comparator

2017-11-19 08:08 UTC, AleksandrRadchenko approved these changes

2017-11-19 15:19 UTC, ferventdev approved these changes

2017-11-20 10:55 UTC, elefus approved these changes

2017-11-20 10:55 UTC, merged