Lambda.part3.exercise4 (Radchenko)
elefus/epam-lab-java8-11-2017 pull request #71
Opened 2017-11-18 21:31 UTC by Alsturm

2017-11-19 15:19 UTC, ferventdev approved these changes

2017-11-19 20:11 UTC, usilitel approved these changes

2017-11-21 10:13 UTC, elefus requested changes
Выделить общую часть и вынести в отдельный метод

2017-11-21 10:13 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +        public <U2> LazyFlatMapHelper<T, U2> map(final Function<R, U2> mapping) {
Не кажется ли код в методах `flatMap`, `map` и `force` очень похожим?
Возможно стоит задуматься о принципе DRY и выделить общую часть с вынесением её в отдельный метод?

2017-11-21 12:35 UTC, Alsturm commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +        public <U2> LazyFlatMapHelper<T, U2> map(final Function<R, U2> mapping) {
DRY применили, но потеряли KISS... :(

2017-11-21 12:35 UTC, Alsturm commented
Fixed

2017-11-27 11:17 UTC, elefus approved these changes

2017-11-27 11:17 UTC, merged