Lambda.part3.exercise4 (Nikolaev)
elefus/epam-lab-java8-11-2017 pull request #81
Opened 2017-11-19 20:04 UTC by usilitel

2017-11-20 06:56 UTC, ferventdev approved these changes

2017-11-21 10:07 UTC, elefus requested changes
Посмотри замечания

2017-11-21 10:07 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            return new LazyFlatMapHelper<>(list, Arrays::asList);
В качестве начального способа преобразования элемента в список ты используешь `Arrays.asList` - он работает с собственной неизменяемой реализацией `ArrayList`.
Однако, для представления всего одного элемента в виде списка наиболее эффективной будет реализация, предоставляемая методом `Collections.<T>singletonList(T)`.

2017-11-21 10:07 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +        public <U> LazyFlatMapHelper<T, U> map(Function<R, U> mapping) {
Не кажется ли код в методах `flatMap`, `map` и `force` очень похожим?
Возможно стоит задуматься о принципе DRY и выделить общую часть с вынесением её в отдельный метод?

2017-11-28 12:41 UTC, petriankins approved these changes

2017-12-27 08:33 UTC, elefus approved these changes

2017-12-27 08:33 UTC, merged