Lambda part3 task1
elefus/epam-lab-java8-11-2017 pull request #88
Opened 2017-11-20 15:47 UTC by super64812

2017-11-30 13:10 UTC, elefus requested changes
Изменить способ комбинирования функций.

2017-11-30 13:10 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = employee -> stringLengthExtractor.apply(fullNameExtractor.apply(employee));
Комбинировать функции следует через andThen.

2017-12-07 07:41 UTC, elefus requested changes
Посмотри замечания

2017-12-07 07:41 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        List<Integer> lengths = new ArrayList<>();
В конструкторе можно сразу задать `capacity`, т.к. размер изначального списка известен.

2017-12-07 07:41 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = employee -> fullNameExtractor.andThen(stringLengthExtractor).apply(employee);
Использование `employee ->` и потом вызов `.apply(employee)` избыточен.
Комбинирование функций порождает новую функцию как раз с требуемой сигнатурой.

2018-01-13 13:12 UTC, super64812 commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = employee -> fullNameExtractor.andThen(stringLengthExtractor).apply(employee);
Done.

2018-01-15 10:12 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise1.java
> +        Function<Employee, Integer> fullNameLengthExtractor = employee -> fullNameExtractor.andThen(stringLengthExtractor).apply(employee);
Но ведь не Done =)
Может забыл закоммитить?

2018-01-15 10:44 UTC, elefus approved these changes

2018-01-15 10:44 UTC, merged