Lambda.part3.exercise4 (Bevad)
elefus/epam-lab-java8-11-2017 pull request #91
Opened 2017-11-20 19:07 UTC by Ksenomorfa

2017-11-21 09:52 UTC, elefus requested changes
Посмотри замечания

2017-11-21 09:52 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +                    for (U u : flatMapping.apply(r)) {
Для того чтобы добавить все элементы из некоторой коллекции в список следует использовать метод `List<E>.addAll(Collection<E>)` - он выполняет копирование блока данных наиболее оптимальным способом. Для `ArrayList`, например, это будет копирование всего внутреннего массива с помощью `System.arraycopy`.

2017-11-21 09:52 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            final List<R> result = new ArrayList<>();
Не кажется ли код в методах `flatMap`, `map` и `force` очень похожим?
Возможно стоит задуматься о методе DRY и выделить общую часть с вынесением её в отдельный метод?

2017-11-21 09:52 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            return new LazyFlatMapHelper<>(list, Arrays::asList);
В качестве начального способа преобразования элемента в список ты используешь Arrays.asList - он работает с собственной неизменяемой реализацией ArrayList.
Однако, для представления всего одного элемента в виде списка наиболее эффективной будет реализация, предоставляемая методом `Collections.<T>singletonList(T)`.

2017-11-23 12:46 UTC, Ksenomorfa commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            return new LazyFlatMapHelper<>(list, Arrays::asList);
Спасибо, пофиксила.

2017-11-23 12:46 UTC, Ksenomorfa commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +                    for (U u : flatMapping.apply(r)) {
Сделано.

2017-11-23 12:48 UTC, Ksenomorfa commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            final List<R> result = new ArrayList<>();
Кажется, что похожи, но как это выделить, с условием различных типов  U/R/T/List<U>, не представляю. Плюс доп. проходы с addAll по сравнению c force присутствуют. Можно наводку?

2017-12-27 08:34 UTC, elefus commented on src/test/java/lambda/part3/exercise/Exercise4.java
> +            final List<R> result = new ArrayList<>();
Попробуй создать не-статический метод с сигнатурой `public <A, B> List<B> force(List<A> source, Function<A, List<B>> remapping)` и вынести в него тело существующего в данный момент метода `force`.
А далее, комбинируя накопленные к моменту вызова преобразования `this.flatMapping` и этот метод, реализовать `map` и `flatMap`.

2017-12-27 08:35 UTC, elefus approved these changes

2017-12-27 08:35 UTC, merged